WebUI/Controllers/ClientToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;
using static System.Net.Mime.MediaTypeNames; 
using System.Resources;
using System.Globalization;
using WebUI.Filter;

namespace Kids.WebUI.Controllers
{

    public class ClientToolsController : Controller
    {

        private struct ColumnObjectStruct
        {
            public string headerText { get; set; }
            public bool hidden { get; set; }
            public string key { get; set; }
            public string dataType { get; set; }
            public string width { get; set; }
            public bool filterable { get; set; }
        }



        #region For Search

        //public JsonResult Find(string moduleCode, string Condition, string controlName)
        //{
        //    SystemTools sys = new SystemTools();

        //    var obj = sys.SearchProperties(moduleCode, controlName);
        //    if (obj.Settings.DataSourceName == null)
        //    {
        //        return Shared.JsonObject(null);
        //    }
        //    string cols = string.Empty;

        //    List<ColumnObjectStruct> columnsObject = new List<ColumnObjectStruct>();
        //    columnsObject.Add(new ColumnObjectStruct()
        //    {
        //        dataType = "number",
        //        headerText = "",
        //        hidden = true,
        //        key = "RowIndex",
        //        width = "0"
        //    });
        //    foreach (G_SearchFormSetting column in obj.Columns)
        //    {
        //        if ((column.Language == 0) ||
        //            (SessionManager.SessionRecord.ScreenLanguage == "en" && column.Language == 2) ||
        //            (SessionManager.SessionRecord.ScreenLanguage == "ar" && column.Language == 1))
        //        {
        //            cols += "," + column.DataMember;
        //            ColumnObjectStruct colObj = new Controllers.ClientToolsController.ColumnObjectStruct();
        //            colObj.dataType = column.Datatype == 0 ? "string" : "number";

        //            if (SessionManager.SessionRecord.ScreenLanguage == "en")
        //                colObj.headerText = column.FieldTitle;
        //            else
        //                colObj.headerText = column.FieldTitleA;

        //            colObj.hidden = !column.IsReadOnly;
        //            colObj.filterable = false;
        //            colObj.key = column.DataMember;
        //            colObj.width = column.FieldWidth == 0 ? "100px" : (column.FieldWidth.ToString() + "px");

        //            columnsObject.Add(colObj);
        //        }
        //    }

        //    string tableName = obj.Settings.DataSourceName;
        //    string condition = "";

        //    if (Condition == null || Condition == "")
        //        condition = "";
        //    else
        //        condition = " Where " + Condition;

        //    string columns = cols.Substring(1);
        //    string orderBy = obj.Settings.ReturnDataPropertyName;

        //    var result = sys.Find(tableName, condition, columns, orderBy);

        //    var resultObject = new
        //    {
        //        TableName = tableName,
        //        Condition = condition,
        //        DataResult = result,
        //        Settings = obj.Settings,
        //        Columns = columnsObject

        //    };
        //    var jsonResult = Shared.JsonObject(resultObject);
        //    return jsonResult;
        //}


        //public JsonResult GetByIndex(string tableName, string Condition, int index, bool ChangePageIndex)
        //{
        //    SystemTools sys = new SystemTools();
        //    var result = sys.GetByIndex(tableName, Condition, index);
        //    var jsonResult = Shared.JsonObject(result);
        //    if (ChangePageIndex == true)
        //        SessionManager.PageIndex = index;
        //    return jsonResult;
        //}

        //public JsonResult GetIndexByUseId(string idValue, string BaseTableName, string idFieldName)
        //{
        //    SystemTools sys = new SystemTools();
        //    string _Result = sys.GetIndexByUseId(int.Parse(idValue), BaseTableName, idFieldName);
        //    return Shared.JsonObject(_Result);
        //}
        //public JsonResult GetIndexByUseCode(string idValue, string BaseTableName, string idFieldName,string condition)
        //{
        //    SystemTools sys = new SystemTools();
        //    string _Result = sys.GetIndexByUseCode(idValue, BaseTableName, idFieldName, condition);
        //    return Shared.JsonObject(_Result);
        //}

        #endregion




        //public JsonResult Refilter(string moduleCode, string Condition, string controllerName)
        //{
        //    var result = this.Find(moduleCode, Condition.Replace("Where", ""), controllerName);
        //    return result;
        //}
        //public JsonResult GetActionUrl(string actionName, string controllerName)
        //{
        //    string result = Url.Action(actionName, controllerName);
        //    return Shared.JsonObject(result);
        //}
        //public void SetValueToSession(string key, object value)
        //{
        //    Session[key] = value;
        //}
        public JsonResult GetResourceByName(string key)
        {
            //SystemResource.ResourceManager.IgnoreCase = true;
            //string result = SystemResource.ResourceManager.GetString(key);
            return Shared.JsonObject("ok");
        }
        public JsonResult GetResourceNames(string _prefix)
        {
            Dictionary<string, string> dicResources = new Dictionary<string, string>();
            ResourceManager MyResourceClass = new ResourceManager(typeof(SystemResource));

            ResourceSet resourceSet = MyResourceClass.GetResourceSet(CultureInfo.CurrentUICulture, true, true);
            foreach (DictionaryEntry entry in resourceSet)
            {
                if (entry.Key.ToString().Contains(_prefix))
                {
                    string resourceKey = entry.Key.ToString();
                    string resourceValue = entry.Value.ToString();

                    dicResources.Add(resourceKey, resourceValue);
                }
            }
            return Shared.JsonObject(dicResources);
        }
        public JsonResult LogOut()
        {
            //Session.Clear();
            var obj = Shared.JsonObject(Url.Action("LoginIndex", "Login"));
            return obj;
        }

        private class SystemResource
        {
 
        }
        

    }
}

WebUI/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <link rel="shortcut icon" href="~/images/logokids.png">
    <link rel="stylesheet" type="text/css" href="~/login/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="~/login/css/bootstrap.min.css" />

    <link rel="stylesheet" type="text/css" href="~/login/css/login.css" />

    <link rel="stylesheet" type="text/css" href="~/login/css/component.css" />
    <link href='http://fonts.googleapis.com/css?family=Raleway:200,400,800|Clicker+Script' rel='stylesheet' type='text/css'>
    <link href="~/login/css/hover.css" rel="stylesheet" media="all">
    <link type="text/css" rel="stylesheet" href="~/css/waitMe.css">
    <link href="~/css/background.css" rel="stylesheet" />

</head>
<body>
    <script src="~/ClientApp/App.js"></script>
    <script src="~/ClientApp/SystemTools.js"></script>
    <script src="~/ClientApp/Entities.js"></script>
    <script src="~/ClientApp/Shared.js"></script>
    <script src="~/ClientApp/AjaxCaller.js"></script>
 
    <div>
        @RenderBody()
    </div>

    <script src="~/js/waitMe.js"></script>
    <script type="text/javascript" src="~/login/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/login/js/login.js"></script>

    <script>
        $(document).ready(function (e) {
            setTimeout(function () {
                $(".container_login").removeClass("flip");
                $(".container_login").addClass("flip_re");
            });

        });
    </script>

    <!--.............................clock...........................-->
    <script type="text/javascript">
        $(document).ready(function () {
            var monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
            var dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

            var newDate = new Date();
            newDate.setDate(newDate.getDate());
            $('#Date').html(dayNames[newDate.getDay()] + " " + newDate.getDate() + ' ' + monthNames[newDate.getMonth()] + ' ' + newDate.getFullYear());

            setInterval(function () {
                var seconds = new Date().getSeconds();
                $("#sec").html((seconds < 10 ? "0" : "") + seconds);
            }, 1000);

            setInterval(function () {
                var minutes = new Date().getMinutes();
                $("#min").html((minutes < 10 ? "0" : "") + minutes);
            }, 1000);

            setInterval(function () {
                var hours = new Date().getHours();
                $("#hours").html((hours < 10 ? "0" : "") + hours);
            }, 1000);

        });
    </script>

    <script src="~/login/js/rAF.js"></script>
    <script src="~/login/js/demo-2.js"></script>

    <input type="hidden" id="GetActionUrl" name="name" value="@Url.Action("GetActionUrl","ClientTools")" />
</body>
</html>

WebUI/Views/Shared/Popup.cshtml
@*@using Inv.WebUI.Resources*@
@*//eslam 2 nov 2020*@

<html>
<head>
  
</head>

<body>

    <div class="modal fade" id="PopupDialog" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div id="PopupBody" class=" modal-body col-lg-12 col-xs-12 ">


                </div>
            </div>
        </div>
    </div>

 
 
</body>
</html>

WebUI/Views/Shared/Popuppicture.cshtml
@*@using Inv.WebUI.Resources*@
@*//eslam 2 nov 2020*@

<html>
<head>

    <link href="~/Scripts/JsGrid/jsgrid.min.css" rel="stylesheet" />
    <link href="~/Scripts/JsGrid/jsgrid-theme.min.css" rel="stylesheet" />
    <link href="~/Scripts/jsgrid/jsgrid-theme.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />


</head>

<body>

    <div class="modal fade" id="PopupDialogpicture" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div id="Bodypicture" class=" modal-body col-lg-12 col-xs-12 " style="width: 80%;">
                    <button style="margin-top: 3px;" type="button" class="close" data-dismiss="modal">&times;</button>


                </div>
            </div>
        </div>
    </div>


    @*datatable For search*@

    <script src="~/Style_design/js/vendor/jquery-1.11.3.min.js"></script>
    <script src="~/ClientApp/JsGrid.js"></script>
    <script src="~/Scripts/jsgrid/jsgrid.js"></script>
    @*<script src="~/js/my_js.js"></script>*@
    <script src="~/js/bootstrap.min.js"></script>

    <!-- bootstrap JS
    ============================================ -->
    <script src="~/Style_design/js/bootstrap.min.js"></script>
    <!-- meanmenu JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.meanmenu.js"></script>
    <!-- mCustomScrollbar JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- sticky JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.sticky.js"></script>
    <!-- scrollUp JS
    ============================================ -->
    <script src="~/Style_design/js/jquery.scrollUp.min.js"></script>
    <!-- counterup JS
    ============================================ -->
    <script src="~/Style_design/js/counterup/jquery.counterup.min.js"></script>
    <script src="~/Style_design/js/counterup/waypoints.min.js"></script>
    <!-- dropzone JS
    ============================================ -->
    <script src="~/Style_design/js/dropzone.js"></script>
    <!-- multiple email JS
    ============================================ -->
    <script src="~/Style_design/js/multiple-email/multiple-email-active.js"></script>
    <!-- summernote JS
    ============================================ -->
    <script src="~/Style_design/js/summernote.min.js"></script>
    <script src="~/Style_design/js/summernote-active.js"></script>
    <!-- main JS
    ============================================ -->
    <script src="~/Style_design/js/vendor/modernizr-2.8.3.min.js"></script>
    @*End Data table*@
</body>
</html>

WebUI/Views/Shared/_ErrorPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script>
        $(document).ready(function () {
            var error = getParameterByName("err");
            if (error != null) {
                $("#divError").css("display", "");
                $("#divError").text(error);
            }
        });

        function getParameterByName(name, url) {
            if (!url) url = window.location.href;
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }
    </script>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <div id="divError" style="display:none;">

    </div>
</body>
</html>